# 서비스 객체의 매니페스트
apiVersion: v1 # 생성할 객체의 api 버전
kind: Service # 생성할 객체의 유형
metadata:
  name: careerwry-posting # 서비스 이름. 고유한 DNS 이름이어야 한다
  labels:
    app: careerwry-posting # 서비스에 부여할 레이블
spec:
  type: ClusterIP # 서비스 유형. ClusterIP, NodePort, LoadBalancer, ExternalName 중 하나를 선택
  selector:
    app: careerwry-posting # 대상으로 삼고 노출해야 하는 파드를 찾는 데 사용할 레이블
  ports:
    - protocol: TCP # 서비스가 사용할 네트워크 프로토콜
      port: 80 # 서비스가 노출할 포트
      targetPort: 9002 # 서비스의 대상이 되는 파드가 노출할 포트